### ISSUE TITLE
Sample Code to convert image into GeoTIFF

### ISSUE THREAD

**Issue by wasimusu** [BeamIO-Inc/resippy#21]
I work with JPG / TIFF images with metadata pertaining to location like latitude, longitude, attitude, etc. 
Do you have sample code to convert TIFF or JPEG images with metadata into GeoTIFF?

**Comment by ryanlaclair** [comment]
I added these tasks to #18 to be included in our final documentation. I am closing this issue - it can be tracked through the existing #18.
